FROM python:3.6-alpine

LABEL maintainer="David Smith <dasmthc@amazon.co.uk"

ENV ALPINE_VERSION=3.6
ENV PACKAGES="\
	curl \
	imagemagick \
	unzip \
"

# replacing default repositories with edge ones
RUN echo \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" > /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories

# Add the packages, with a CDN-breakage fallback if needed
RUN echo \
    && apk add --no-cache $PACKAGES || \
        (sed -i -e 's/dl-cdn/dl-4/g' /etc/apk/repositories && apk add --no-cache $PACKAGES)

# turn back the clock
RUN echo \
    && echo "http://dl-cdn.alpinelinux.org/alpine/v$ALPINE_VERSION/main/" > /etc/apk/repositories

RUN echo \
    && echo "@edge-testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
    && echo "@edge-community http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
    && echo "@edge-main http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories

WORKDIR /

RUN apk del curl unzip

RUN pip install --upgrade pip
RUN pip install awscli

ADD ./code/*.pip /code/
RUN echo \
    && pip install --no-cache-dir -r /code/*.pip