FROM gettyimages/spark

LABEL maintainer="David Smith <dasmthc@amazon.co.uk"

#RUN apt-get update
#RUN apt-get upgrade -y

RUN pip install --upgrade pip
RUN pip install awscli

ADD ./code/*.pip /code/
RUN echo \
    && pip install --no-cache-dir -r /code/*.pip
